/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-dim": "#ee7d6e",
        "outline-variant": "#484848",
        "on-secondary-container": "#b1de83",
        "surface-container-lowest": "#000000",
        "inverse-on-surface": "#555555",
        "secondary-fixed": "#c0ee91",
        "surface-tint": "#ff8e7f",
        "on-error-container": "#ffb2b9",
        "tertiary-fixed-dim": "#e49a71",
        "surface-container-highest": "#262626",
        "on-surface-variant": "#acabaa",
        "error-container": "#a70138",
        "on-secondary-fixed-variant": "#3e6418",
        "surface": "#0e0e0e",
        "secondary": "#c0ee91",
        "primary-fixed": "#ff8a7a",
        "secondary-dim": "#b2df85",
        "background": "#0e0e0e",
        "on-tertiary-fixed-variant": "#653211",
        "surface-container-high": "#1f2020",
        "surface-container-low": "#131313",
        "secondary-container": "#2c5003",
        "on-tertiary-container": "#5a2909",
        "surface-variant": "#262626",
        "inverse-primary": "#9f4135",
        "on-primary-container": "#4d0402",
        "primary-container": "#f28070",
        "inverse-surface": "#fcf9f8",
        "primary": "#ff8e7f",
        "primary-fixed-dim": "#ee7d6e",
        "on-secondary": "#35590e",
        "on-surface": "#ffffff",
        "error": "#ff6e84",
        "error-dim": "#d73357",
        "on-primary-fixed-variant": "#671710",
        "tertiary-dim": "#e49a71",
        "surface-bright": "#2c2c2c",
        "on-tertiary": "#653212",
        "on-primary-fixed": "#2c0000",
        "on-primary": "#5e100a",
        "on-secondary-fixed": "#254600",
        "surface-dim": "#0e0e0e",
        "on-tertiary-fixed": "#3b1500",
        "surface-container": "#191a1a",
        "tertiary-fixed": "#f3a77d",
        "on-error": "#490013",
        "tertiary": "#ffb68e",
        "on-background": "#ffffff",
        "outline": "#767575",
        "secondary-fixed-dim": "#b2df85",
        "tertiary-container": "#f3a77d"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
